backend:
  name: git-gateway
  repo: Slashmore87/bmasv-portfolio   #  <-- tu usuario / repo
  branch: main

media_folder: "_include/img"          # subidas reales
public_folder: "/_include/img"        # ruta pública

collections:
  - name: "proyectos"
    label: "Proyectos"
    folder: "proyectos"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Título",   name: "title",  widget: "string" }
      - { label: "Año",      name: "year",   widget: "number" }
      - { label: "Descripción", name: "description", widget: "text" }
      - label: "Imagen full"
        name: "imagen_full"
        widget: "image"
        media_folder: "_include/img/work/full"
        public_folder: "/_include/img/work/full"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        media_folder: "_include/img/work/thumbs"
        public_folder: "/_include/img/work/thumbs"

  - name: "publicaciones"
    label: "Publicaciones"
    folder: "publicaciones"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Año",    name: "year",  widget: "number" }
      - { label: "Descripción", name: "description", widget: "text" }
      - label: "Imagen full"
        name: "imagen_full"
        widget: "image"
        media_folder: "_include/img/prensa/full"
        public_folder: "/_include/img/prensa/full"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        media_folder: "_include/img/prensa/thumbs"
        public_folder: "/_include/img/prensa/thumbs"
