backend:
  name: git-gateway
  branch: main

media_folder: "_include/img"
public_folder: "/_include/img"

collections:
  - name: "proyectos"
    label: "Proyectos"
    folder: "proyectos"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Año", name: "year", widget: "number"}
      - {label: "Descripción", name: "description", widget: "text"}
      - label: "Imágenes full"
        name: "imagen_full"
        widget: "list"
        field:
          label: "Imagen"
          name: "image"
          widget: "image"
          media_folder: "/_include/img/work/full"
          public_folder: "/_include/img/work/full"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        media_folder: "/_include/img/work/thumbs"
        public_folder: "/_include/img/work/thumbs"
      - label: "Filtro"
        name: "filtro"
        widget: "select"
        options:
          - { label: "Concurso", value: "con" }
          - { label: "Asesoría", value: "ase" }
          - { label: "Arquitectura", value: "arq" }
          - { label: "Licitaciones", value: "lic" }
  - name: "publicaciones"
    label: "Publicaciones"
    folder: "publicaciones"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Año", name: "year", widget: "number"}
      - {label: "Descripción", name: "description", widget: "text"}
      - label: "Imagen full"
        name: "imagen_full"
        widget: "image"
        media_folder: "_include/img/prensa/full"
        public_folder: "/_include/img/prensa/full"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        media_folder: "_include/img/prensa/thumbs"
        public_folder: "/_include/img/prensa/thumbs"
