backend:
  name: git-gateway
  branch: main

media_folder: "_include/img"
public_folder: "/_include/img"

collections:
  - name: test
    label: "Test Items"
    folder: "test"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}
